- name: Build Auth API
  shell: |
    export GO111MODULE=on
    go mod init github.com/bortizf/microservice-app-example/tree/master/auth-api
    go mod tidy
    go build
  args:
    chdir: /mnt/c/DevopsRumpup/DevOpsRMP/microservice-app-example/auth-api

- name: Execute Auth API
  shell: |
    JWT_SECRET=PRFT AUTH_API_PORT=8000 USERS_API_ADDRESS=http://127.0.0.1:8083 ./auth-api 
  async: 1500
  poll: 0
  args:
    chdir: /mnt/c/DevopsRumpup/DevOpsRMP/microservice-app-example/auth-api