- name: Check if OpenJDK 8 is installed
  command: java -version 2>&1 | grep 'openjdk version "1.8'
  register: java_check
  failed_when: false

- name: Install OpenJDK 8
  apt:
    name: openjdk-8-jdk
    state: present
    update_cache: yes
  when: java_check.rc != 0

- name: Build Users API
  command: ./mvnw clean install
  args:
    chdir: /mnt/c/DevopsRumpup/DevOpsRMP/microservice-app-example/users-api
    # java -jar target/users-api-0.0.1-SNAPSHOT.jar JWT_SECRET=PRFT SERVER_PORT=8083

- name: Execute Users API
  shell: |
    JWT_SECRET=PRFT SERVER_PORT=8083 java -jar target/users-api-0.0.1-SNAPSHOT.jar
  poll: 0
  async: 1500
  args:
    chdir: /mnt/c/DevopsRumpup/DevOpsRMP/microservice-app-example/users-api