FROM openjdk:8-jdk-alpine

WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw  pom.xml ./
COPY src ./src

RUN ./mvnw clean install -e 

ENV JWT_SECRET=PRFT \
    SERVER_PORT=8083

RUN chmod +x target/users-api-0.0.1-SNAPSHOT.jar

CMD ["java" , "-jar", "target/users-api-0.0.1-SNAPSHOT.jar"]